package models

// A schema.org Recipe object
//
// The definition for this type is from [Schema.org - Recipe]. This struct
// was auto-generated by inputting its [JSON Schema] into [json-to-go].
//
// [Schema.org - Recipe]: https://schema.org/Recipe
// [JSON Schema]: https://raw.githubusercontent.com/geraintluff/schema-org-gen/master/schema.org/Recipe.json
// [json-to-go]: https://transform.tools/json-to-go
type SchemaRecipe struct {
	CookTime      string   `json:"cookTime"`
	CookingMethod string   `json:"cookingMethod"`
	Ingredients   []string `json:"ingredients"`
}

type SchemaRecipeIngredient struct {
}

type Schema struct {
	// Usually "schema.org"
	Context string `json:"@context"`
	Id      string `json:"@id"`
	// Type can be a string or a list of strings
	Type interface{} `json:"@type"`
}
