FROM node:18-alpine
RUN apk --no-cache add git bash go
COPY --from=golang:1.18-alpine /usr/local/go/ /usr/local/go/ 
ENV PATH="/usr/local/go/bin:${PATH}"

RUN go install github.com/swaggo/swag/cmd/swag@v1.8.1
RUN mv ~/go/bin/swag /usr/local/bin/
RUN npm install -g pnpm

WORKDIR /app
COPY ./ .

RUN pnpm install
RUN pnpm swag:web

WORKDIR /app/apps/web
RUN npx vite build

CMD [ "node", "/app/apps/web/dist/assets/index.*.js" ]


