FROM node:18-alpine
RUN apk --no-cache add git bash

RUN npm install -g pnpm

WORKDIR /app

# Copy all dependency related files and install dependencies
COPY package.json ./
COPY pnpm* ./
COPY apps/web/package.json ./apps/web/
COPY libs/ts/api-fetch/package.json ./libs/ts/api-fetch/

RUN pnpm install
RUN vite build

COPY ./ .

CMD [ "node", "/app/apps/api/web/dist/server.js" ]


