FROM node:18-alpine
RUN apk --no-cache add git bash

RUN npm install -g pnpm

WORKDIR /app

# Copy all dependency related files and install dependencies
COPY package.json ./
COPY .npmrc ./
COPY pnpm* ./
COPY apps/web/package.json ./apps/web/
COPY libs/ts/api-fetch/package.json ./libs/ts/api-fetch/

RUN pnpm install

COPY ./ .

# RUN npx nx run ts-api-fetch:build-fetch
WORKDIR /app/libs/ts/api-fetch
RUN pnpm run codegen && pnpm run build-fetch

WORKDIR /app/apps/web
CMD [ "npx", "vite" ]


