FROM node:20-alpine3.17 as build
RUN apk --no-cache add git bash
RUN npm install -g pnpm

WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

FROM build
# NEXT_PUBLIC_AUTH0 build-time vars
ENV NEXT_PUBLIC_AUTH0_PROFILE=/app/auth/me
ENV NEXT_PUBLIC_AUTH0_LOGIN=/app/auth/login

WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

COPY ./libs/reserved-words ./apps/web/public
COPY ./libs/ts/api-fetch ./libs/ts/api-fetch
RUN pnpm --filter @4ks/api-fetch build

COPY ./apps/web ./apps/web

# RUN pnpm --filter @4ks/web build
# CMD [ "pnpm", "--filter", "@4ks/web", "start" ]

CMD [ "pnpm", "--filter", "@4ks/web", "dev" ]
EXPOSE 3000
