FROM node:18-alpine
RUN apk --no-cache add git bash go
COPY --from=golang:1.18-alpine /usr/local/go/ /usr/local/go/ 
ENV PATH="/usr/local/go/bin:${PATH}"

RUN npm install -g pnpm

WORKDIR /app

# Copy all dependency related files and install dependencies
COPY package.json ./
COPY pnpm* ./
COPY apps/web/package.json ./apps/web/
COPY libs/ts/api-fetch/package.json ./libs/ts/api-fetch/

RUN pnpm install
RUN pnpm swag
RUN vite build

COPY ./ .

CMD [ "node", "/app/apps/api/web/dist/server.js" ]


