# @name Get Recipe
GET https://local.4ks.io/api/recipes/BNYpWruxPACWT5byWD6f HTTP/1.1
content-type: application/json

###

# @name Get Recipe Revisions
GET https://local.4ks.io/api/recipes/BNYpWruxPACWT5byWD6f/revisions HTTP/1.1
content-type: application/json

###

# @name Get Recipe Revision By Id

GET https://local.4ks.io/api/recipes/revisions/M8TOnSAlFiD1woEa4mia HTTP/1.1
Content-Type: application/json 

###

# @name Create Recipe
POST https://local.4ks.io/api/recipes HTTP/1.1
content-type: application/json

{
    "name": "Hammad's Recipe"
}

###

# @name Star Recipe
POST https://local.4ks.io/api/recipes/BNYpWruxPACWT5byWD6f/star HTTP/2.0
Content-Type: application/json

{
    "user": {
        "id": "someId2",
        "username": "someusername",
        "displayName": "somedisplayname"
    }
}