@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImlhZWF2SFpTYlRkbk5DUmlIY1JwQiJ9.eyJodHRwczovLzRrcy5pby9lbWFpbCI6ImhhbW1hZEA0a3MuaW8iLCJpc3MiOiJodHRwczovLzRrcy1kZXYudXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA2OTc5MjQ0ODY1MDc0NjA4MzQ5IiwiYXVkIjpbImh0dHBzOi8vbG9jYWwuNGtzLmlvL2FwaSIsImh0dHBzOi8vNGtzLWRldi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjUzOTUwOTYxLCJleHAiOjE2NTQwMzczNjEsImF6cCI6ImVNNVp5eWZwNmNvTGczek9STUZzWkVuUW1wcXhCakhkIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.lKmW9Oh3EWs1z8BpW5BbNhIu7x_rM3D0N-lME-IKcJcntdXSjrrcI4xN9VOcFFjdj4Pu6Pzjg2ZyGwX7pqNyEQniGwj9Kr4Gn_RMtpbh99MB4OgBjK9r2_feTIJAQ-NTFbjhOEAW6earHp5-FTdRv9w8bEerFsBiV2e9Y3loWstMpCaQERboxbx9fxh7WLXFN0lfHU5zNFzJ-iQPqxs4K_Kt0kajPVrMzZ8aMv1iUHzRwEj1RHi4rq2qVCmE-RVjoPWqyd1h7YWBiS9h0p8rKPO8dHLepoy1tFjhoHt1LBEonXrWeKIynrOgJGZtUwhCP0s_yw74FsB8kUygaYJdxQ

###

# @name Get Recipe
GET https://local.4ks.io/api/recipes/BNYpWruxPACWT5byWD6f HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}
###

# @name Get Recipe Revisions
GET https://local.4ks.io/api/recipes/txlATtVaSXYxEOPVxNBR/revisions HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###

# @name Get Recipe Revision By Id

GET https://local.4ks.io/api/recipes/revisions/CogSt9soW2eXvxW7lgNn HTTP/1.1
Content-Type: application/json 
Authorization: Bearer {{authToken}}

###

# @name Create Recipe
POST https://local.4ks.io/api/recipes HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Hammad's Recipe"
}

###

# @name Star Recipe
POST https://local.4ks.io/api/recipes/BNYpWruxPACWT5byWD6f/star HTTP/2.0
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "user": {
        "id": "someId2",
        "username": "someusername",
        "displayName": "somedisplayname"
    }
}

###

# @name Auth Test
GET https://local.4ks.io/api/auth-test
Authorization: Bearer {{authToken}}
