version: '3.9'
services:
  nginx:
    container_name: 4ks-alb
    build: ./dev/apps/nginx
    image: 4ks/alb
    ports:
      - '443:4433'
      - '80:8080'
    restart: always
    # logging:
    #   driver: none
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./dev/apps/nginx/local.4ks.io.pem:/etc/nginx/conf.d/local.4ks.io.pem
      - ./dev/apps/nginx/local.4ks.io.key:/etc/nginx/conf.d/local.4ks.io.key
      - ./dev/apps/nginx/local.conf:/etc/nginx/conf.d/local.conf
