#!/bin/bash

curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"userId":"foo","url":"https://www.4ks.io/recipe/OQVsQx0jZ5Qmjl57FOIy-overnight-chocolate-oats"}' \
  http://localhost:5888/test