apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: 4ks-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: 4ks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 4ks-api
  template:
    metadata:
      labels:
        app: 4ks-api
    spec:
      containers:
        - name: 4ks-api
          image: 4ks-api
          env:
            - name: PORT
              value: '5000'
            - name: FIRESTORE_EMULATOR_HOST
              value: firestore:8200
            - name: FIRESTORE_PROJECT_ID
              value: 4ks-dev
            - name: AUTH0_DOMAIN
              value: 4ks-dev.us.auth0.com
            - name: AUTH0_CLIENT_ID
              value: eM5Zyyfp6coLg3zORMFsZEnQmpqxBjHd
            - name: AUTH0_CLIENT_SECRET
              value: AxT9wCGFYRTz38XhhZuVuAKZvoXiNMmPb1WYLeb-SkU90IC6vqJKdgeScbHccGHn
            - name: AUTH0_CALLBACK_URL
              value: https://local.4ks.io/api/authback
            - name: EXPORTER_TYPE
              value: JAEGER
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: '/ready'
