apiVersion: v1
kind: Service
metadata:
  name: fetcher
spec:
  selector:
    app: fetcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  labels:
    app: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher
  template:
    metadata:
      labels:
        app: fetcher
    spec:
      containers:
        - name: fetcher
          image: fetcher
          env:
            - name: PORT
              value: '5000'
            - name: DEBUG
              value: 'true'
            - name: PUBSUB_PROJECT_ID
              value: local-4ks
            - name: PUBSUB_EMULATOR_HOST
              # value: pubsub:8085
              value: pubsub.default.svc.cluster.local:8085
          ports:
            - containerPort: 5000
          # readinessProbe:
          #   httpGet:
          #     port: 5000
          #     path: '/ready'
