apiVersion: v1
kind: Service
metadata:
  name: firestore
spec:
  selector:
    app: firestore
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestore
  labels:
    app: firestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firestore
  template:
    metadata:
      labels:
        app: firestore
    spec:
      containers:
        - name: firestore
          image: mtlynch/firestore-emulator
          env:
            - name: FIRESTORE_PROJECT_ID
              value: 'dev-4ks'
            - name: PORT
              value: '8200'
          ports:
            - containerPort: 8200
          # readinessProbe:
          #   httpGet:
          #     port: 5000
          #     path: '/ready'
