apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: 4ks-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 4ks-frontend
  template:
    metadata:
      labels:
        app: 4ks-frontend
    spec:
      containers:
        - name: 4ks-frontend
          image: 4ks-frontend
          env:
            - name: VITE_CLIENT_PORT
              value: '5735'
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     port: 3000
          #     path: '/'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: 4ks-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000