apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: local.4ks.io
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 3000
    - host: local.4ks.io
      http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: 5000
