apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
        - name: pubsub
          image: google/cloud-sdk:emulators
          command:
            [
              'gcloud',
              'beta',
              'emulators',
              'pubsub',
              'start',
              '--project=local-4ks',
            ]
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
