# https://dev.to/ndrean/rails-on-kubernetes-with-minikube-and-tilt-25ka
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: typesense-pv
#   labels:
#     app: typesense
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /tmp/4ks-typesense-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-pvc
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense
  labels:
    app: typesense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      volumes:
        - name: typesense-pv
          persistentVolumeClaim:
            claimName: typesense-pvc
      containers:
        - name: typesense
          image: typesense/typesense:0.24.0
          volumeMounts:
            - name: typesense-pv
              mountPath: /data
          env:
            - name: TYPESENSE_DATA_DIR
              value: /data
            - name: TYPESENSE_API_KEY
              value: local-4ks-api-key
            - name: TYPESENSE_ENABLE_CORS
              value: 'false'
            # - name: TYPESENSE_CORS_DOMAINS
            #   value: https://local.4ks.io
            # - name: TYPESENSE_ENABLE_ACCESS_LOGGIN
            #   value: 'true'
          ports:
            - containerPort: 8108
          livenessProbe:
            httpGet:
              path: /health
              port: 8108
            initialDelaySeconds: 10
            periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     port: 8108
          #     path: '/health'
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: typesense
spec:
  selector:
    app: typesense
  ports:
    - protocol: TCP
      port: 8108
      targetPort: 8108
# https://typesense.org/docs/0.24.0/api/server-configuration.html#using-command-line-arguments
