apiVersion: v1
kind: Service
metadata:
  name: web-next
spec:
  selector:
    app: web-next
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-next
  labels:
    app: web-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-next
  template:
    metadata:
      labels:
        app: web-next
    spec:
      containers:
        - name: web-next
          image: web-next
          env:
            - name: FOO
              value: bar
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     port: 3000
          #     path: '/'
