FROM node:20-alpine3.17 as build
RUN apk --no-cache add git bash
RUN npm install -g pnpm

WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

FROM build
WORKDIR /code
COPY /PACKAGE_JSON /code
COPY /pnpm* .
RUN pnpm install

COPY ./libs/ts/api-fetch ./libs/ts/api-fetch
RUN pnpm --filter @4ks/api-fetch build

COPY ./apps/web-next ./apps/web-next

# RUN pnpm --filter @4ks/web-next build
# CMD [ "pnpm", "--filter", "@4ks/web-next", "start" ]

CMD [ "pnpm", "--filter", "@4ks/web-next", "dev" ]
EXPOSE 3000
