FROM node:20-alpine3.17
RUN apk --no-cache add git bash
RUN npm install -g pnpm

WORKDIR /code

# Copy all dependency related files and install dependencies
COPY /package.json .
COPY /pnpm* .
COPY /apps/web-next/package.json ./apps/web/
COPY /apps/web-next/pnpm* ./apps/web
COPY /libs/ts/api-fetch/package.json ./libs/ts/api-fetch/
RUN pnpm install

COPY ./libs/ts/api-fetch ./libs/ts/api-fetch
COPY ./apps/web-next ./apps/web

RUN pnpm --filter @4ks/api-fetch build

CMD [ "pnpm", "--filter", "@4ks/web-next", "dev" ]
EXPOSE 3000
