apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: 4ks-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: 4ks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 4ks-api
  template:
    metadata:
      labels:
        app: 4ks-api
    spec:
      containers:
        - name: 4ks-api
          image: 4ks-api
          env:
            - name: PORT
              value: '5000'
            - name: GIN_MODE
              value: debug
            - name: JAEGER_ENABLED
              value: 'false'
            - name: SWAGGER_ENABLED
              value: 'true'
            - name: SWAGGER_URL_PREFIX
              value: '/api'
            - name: FIRESTORE_EMULATOR_HOST
              value: firestore.default.svc.cluster.local:8200
            - name: FIRESTORE_PROJECT_ID
              value: local-4ks
            - name: PUBSUB_PROJECT_ID
              value: local-4ks
            - name: PUBSUB_EMULATOR_HOST
              value: pubsub.default.svc.cluster.local:8085
            - name: AUTH0_DOMAIN
              value: 4ks-dev.us.auth0.com
            - name: AUTH0_AUDIENCE
              value: 'https://local.4ks.io/api'
            - name: EXPORTER_TYPE
              value: JAEGER
            - name: VERSION_FILE_PATH
              value: apps/api/VERSION
            - name: UPLOADABLE_BUCKET
              value: media-write.sbx.4ks.io
            - name: DISTRIBUTION_BUCKET
              value: media-read.sbx.4ks.io
            - name: STATIC_MEDIA_BUCKET
              value: static.dev.4ks.io
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /code/google-app-creds.json
            - name: TYPESENSE_URL
              value: http://typesense.default.svc.cluster.local:8108
            - name: TYPESENSE_API_KEY
              value: local-4ks-api-key
            - name: IO_4KS_DEVELOPMENT
              value: 'true'
            - name: MEDIA_FALLBACK_URL
              value: https://storage.googleapis.com/static.dev.4ks.io
            - name: API_FETCHER_PSK
              # must match fetcher.API_FETCHER_PSK
              value: 2c44a496343cfc994d325cd135cba995
            - name: FETCHER_HEADER_KEY
              # must match fetcher.API_HEADER_KEY
              value: X-4ks-Auth
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: '/api/ready'
