apiVersion: v1
kind: Service
metadata:
  name: firestore
spec:
  selector:
    app: firestore
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestore
  labels:
    app: firestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firestore
  template:
    metadata:
      labels:
        app: firestore
    spec:
      containers:
        - name: firestore
          # image: mtlynch/firestore-emulator
          image: google/cloud-sdk:emulators
          command: ['gcloud', 'beta', 'emulators', 'firestore', 'start']
          args: ['--host-port=0.0.0.0:8200']
          env:
            - name: FIRESTORE_PROJECT_ID
              value: 'local-4ks'
            # - name: PORT
            #   value: '8200'
          ports:
            - containerPort: 8200
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8085
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     port: 8200
          #     path: '/'
