apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: '9411'
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: '5775'
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: '6831'
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: '6832'
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: '5778'
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: '16686'
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: '14250'
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: '14268'
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: '14269'
      protocol: TCP
      port: 14269
      targetPort: 14269
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.33
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: '9411'
          ports:
            - containerPort: 8200
          # readinessProbe:
          #   httpGet:
          #     port: 5000
          #     path: '/ready'
