FROM golang:1.20-alpine as build
RUN go install github.com/mitranim/gow@latest

WORKDIR /code
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

FROM build
WORKDIR /code
COPY ./libs/reserved-words/reserved-words ./reserved-words
COPY ./deploy/sbx-4ks-google-app-creds.json ./google-app-creds.json

COPY ./go.mod ./
COPY ./go.sum ./

COPY ./apps/api ./apps/api
COPY ./libs/go ./libs/go
RUN go mod tidy

CMD ["gow", "run", "./apps/api"]