FROM golang:1.20-alpine

RUN go install github.com/mitranim/gow@latest

WORKDIR /code

COPY ./libs/reserved-words/reserved-words ./reserved-words
COPY ./go.mod ./
COPY ./go.sum ./
COPY ./apps/api ./apps/api
COPY ./libs/go ./libs/go

RUN go mod tidy
RUN go build ./apps/api/main.go

CMD ["/code/main"]