name: API CI
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - './(nx|workspace).json'
      - ./go*
      - './apps/api/*'
      - './libs/go/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./apps/api/Dockerfile.ci
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: 4ks/api-ci:latest
          # cache-from: type=registry,ref=4ks/api-ci:buildcache
          # cache-to: type=registry,ref=4ks/api-ci:buildcache,mode=max
