name: WEB CI
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - (nx|packagets|config.base|workspace).json
      - pnpm*
      - apps/web/**
      - libs/ts/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   fetch-depth: 1
      # - shell: bash
      #   run: |
      #     pwd
      #     ls -la
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./apps/web/Dockerfile.ci
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          # tags: 4ks/web-ci:latest
