name: Build and Publish Web Container
# https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
# https://docs.docker.com/build/ci/github-actions/cache/
on:
  workflow_call:
    inputs:
      gcp_project_name:
        description: 'dev-4ks | tst-4ks | prd-4ks | eng-4ks'
        required: true
        type: string
      gcp_registry:
        description: 'container registry url'
        required: true
        type: string
      build_number:
        description: 'build number'
        required: true
        type: string
    secrets:
      gcp_api_token:
        required: true

jobs:
  build:
    name: container
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4
      # setup buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # enable caching
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # package.json hack
      - name: PACKAGE_JSON hack
        run: |
          ./tools/package_json.sh
      # cloud auth
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ inputs.gcp_project_name }}
          credentials_json: ${{ secrets.gcp_api_token }}
      # cloud sdk
      - name: GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      # cloud config
      - name: GCP Config
        run: |
          # gcloud auth configure-docker -q
          gcloud auth configure-docker ${{ inputs.gcp_registry }} --quiet
      # build
      - name: Build Base
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ inputs.build_number }}
          file: ./apps/web/Dockerfile
          push: false
          tags: |
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/web/app:${{ inputs.build_number }}
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/web/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build Base
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ inputs.build_number }}
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/web/app:${{ inputs.build_number }}
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/web/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
