name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'dev | tst | prd'
        required: true
        type: string
      build_number:
        description: 'build number'
        required: true
        type: string
    secrets:
      gcp_api_token:
        required: true

jobs:
  fetcher:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      gcp_api_token: ${{ secrets.gcp_api_token }}
    with:
      app_name: recipe-fetcher
      # environment: ${{ inputs.environment }}
      gcp_project_name: eng-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ inputs.build_number }}
  api:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      gcp_api_token: ${{ secrets.gcp_api_token }}
    with:
      app_name: api
      # environment: ${{ inputs.environment }}
      gcp_project_name: eng-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ inputs.build_number }}
  web:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      gcp_api_token: ${{ secrets.gcp_api_token }}
    with:
      app_name: web
      # environment: ${{ inputs.environment }}
      gcp_project_name: eng-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ inputs.build_number }}
