name: Build and Publish Container

on:
  workflow_call:
    inputs:
      app_name:
        description: 'api | web'
        required: true
        type: string
      # environment:
      #   description: 'dev | tst | prd'
      #   required: true
      #   type: string
      gcp_project_name:
        description: 'dev-4ks | tst-4ks | prd-4ks | eng-4ks'
        required: true
        type: string
      gcp_registry:
        description: 'container registry url'
        required: true
        type: string
      build_number:
        description: 'build number'
        required: true
        type: string
    secrets:
      gcp_api_token:
        required: true

jobs:
  build:
    name: container
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment }}
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3
      # setup buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # enable caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # package.json hack
      - name: PACKAGE_JSON hack
        run: |
          ./tools/package_json.sh
      # cloud auth
      - name: GCP Auth
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ inputs.gcp_project_name }}
          credentials_json: ${{ secrets.gcp_api_token }}
      # cloud sdk
      - name: GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      # cloud config
      - name: GCP Config
        run: |
          # gcloud auth configure-docker -q
          gcloud auth configure-docker ${{ inputs.gcp_registry }} --quiet
      # build
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ inputs.build_number }}
          file: ./apps/${{ inputs.app_name }}/Dockerfile
          push: true
          tags: |
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/${{ inputs.app_name }}/app:${{ inputs.build_number }}
            ${{ inputs.gcp_registry }}/${{ inputs.gcp_project_name }}/${{ inputs.app_name }}/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
