name: main cd
on:
  push:
    branches:
      - main
env:
  TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  REGISTRY: us-east4-docker.pkg.dev/dev-4ks
  ENVIRONMENT: dev
  APP: api
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment version
        run: |
          echo $BUILD_NUMBER
      - name: Pull Latest Alpine Go
        run: docker pull golang:1.18-alpine
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/${{APP}}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          # tags: "$REGISTRY/$APP/app:$BUILD_NUMBER", "$REGISTRY/$APP/app:latest"
          # cache-from: type=registry,ref=4ks/${{APP}}-ci:buildcache
          # cache-to: type=registry,ref=4ks/${{APP}}-ci:buildcache,mode=max
