name: main cd
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-publish.yaml
    with:
      environment: dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
    secrets:
      gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS }}

  dev:
    needs: build
    uses: ./.github/workflows/run-terraform.yaml
    secrets:
      gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS }}
      tf_api_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
    with:
      environment: dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
