name: main cd
on:
  push:
    branches:
      - main
env:
  # can this not be passed to the jobs below??
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  # TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  api:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      cgp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
    with:
      app_name: api
      environment: dev
      gcp_project_name: dev-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  web:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      cgp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
    with:
      app_name: web
      environment: dev
      gcp_project_name: dev-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
