name: main cd
on:
  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  REGISTRY: us-east4-docker.pkg.dev
  PROJECT: dev-4ks
  ENVIRONMENT: dev
jobs:
  api:
    runs-on: ubuntu-latest
    name: build and publish api
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-container
        with:
          app_name: api
          environment: dev
