name: main cd
on:
  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  # TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  # verbose:
  #   name: verbose
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Env Vars
  #       run: |
  #         echo $GITHUB_ENV
  api:
    uses: ./.github/workflows/build-container.yaml
    secrets:
      cgp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
    with:
      app_name: api
      environment: dev
      gcp_project_name: dev-4ks
      gcp_registry: us-east4-docker.pkg.dev
      build_number: "$BUILD_NUMBER"
