name: main cd
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-publish.yaml
    with:
      environment: dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
    secrets:
      gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS_ENG }}

  # dev:
  #   needs: build
  #   uses: ./.github/workflows/run-terraform.yaml
  #   secrets:
  #     gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
  #     tf_api_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  #     typesense_api_key: ${{ secrets.TYPESENSE_API_KEY_DEV }}
  #   with:
  #     environment: dev
  #     build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

  # review:
  #   needs: dev
  #   uses: ./.github/workflows/manual-review.yaml

  prd:
    # needs: dev
    needs: build
    uses: ./.github/workflows/run-terraform.yaml
    secrets:
      gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS_PRD }}
      tf_api_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      typesense_api_key: ${{ secrets.TYPESENSE_API_KEY_PRD }}
      auth0_secret: ${{ secrets.AUTH0_SECRET_PRD }}
      auth0_client_secret: ${{ secrets.AUTH0_CLIENT_SECRET_PRD }}
    with:
      environment: prd
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
