name: main cd
on:
  push:
    branches:
      - main
env:
  # can this not be passed to the jobs below??
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  dev:
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment: dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
    secrets:
      gcp_api_token: ${{ secrets.GOOGLE_CREDENTIALS }}
      tf_api_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
