name: main cd
on:
  push:
    branches:
      - main
env:
  # can this not be passed to the jobs below??
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  # TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  dev:
    uses: ./.github/workflows/deploy-environment.yaml
    secrets:
      cgp_creds: ${{ secrets.GOOGLE_CREDENTIALS }}
    with:
      environment: dev
      build_number: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
