name: main cd
on:
  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  REGISTRY: us-east4-docker.pkg.dev/dev-4ks
  ENVIRONMENT: dev
jobs:
  build:
    env:
      APP: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: |
          echo $BUILD_NUMBER
          local TAGS="$REGISTRY/$APP/app:$BUILD_NUMBER, $REGISTRY/$APP/app:latest"
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Pull Latest Alpine Go
        run: docker pull golang:1.18-alpine
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './apps/$APP/Dockerfile'
          push: true
          login: true
          tags: $TAGS
          # cache-from: type=registry,ref=4ks/${{APP}}-ci:buildcache
          # cache-to: type=registry,ref=4ks/${{APP}}-ci:buildcache,mode=max
