name: review

on:
  workflow_call:

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: publish/app
    steps:
      - name: Manual Review
        uses: actions/github-script@v6
        with:
          script: exit 1
