name: web ci
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - (packagets|config.base|workspace).json
      - pnpm*
      - apps/web/**
      - libs/ts/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest Alpine Node
        run: docker pull node:18-alpine
      - name: Pull Latest Alpine Go
        run: docker pull golang:1.20-alpine
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./apps/web/Dockerfile.ci
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          # tags: 4ks/web-ci:latest
